name: OpenWrt Compatibility Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' 

jobs:
  compatibility-check:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      PLUGIN_PATH: "network/services/luci-app-macfilter"

    steps:
    # ================== 源码准备 ==================
    - name: Checkout LEDE firmware
      uses: actions/checkout@v4
      with:
        repository: coolsnowwolf/lede
        path: lede
        submodules: recursive

    - name: Checkout plugin
      uses: actions/checkout@v4
      with:
        repository: lj8812/luci-app-macfilter
        path: plugin

    # ================== 冲突预检 ==================
    - name: Pre-check conflicts
      run: |
        REQUIRED_FILES=(
          "plugin/luasrc/controller/macfilter.lua"
          "plugin/root/etc/init.d/macfilter"
        )
        for file in "${REQUIRED_FILES[@]}"; do
          if [ ! -f "$file" ]; then
            echo "::error::Missing plugin file: $file"
            exit 1
          fi
        done

        if ! grep -q '^include .*/rules\.mk' plugin/Makefile; then
          echo "::error::Makefile missing include rules.mk"
          exit 1
        fi
        if ! grep -q '^LUCI_DEPENDS' plugin/Makefile; then
          echo "::error::Makefile missing LUCI_DEPENDS"
          exit 1
        fi
        if ! grep -q '^LUCI_TITLE' plugin/Makefile; then
          echo "::error::Makefile missing LUCI_TITLE"
          exit 1
        fi

    # ================== 注入插件 ==================
    - name: Integrate plugin
      run: |
        mkdir -p lede/package/$PLUGIN_PATH
        cp -r plugin/* lede/package/$PLUGIN_PATH/
        find lede/package/$PLUGIN_PATH -type f -exec sed -i 's/\/etc\/config\/MacFilter/\/etc\/config\/macfilter/g' {} +

    # ================== 编译环境 ==================
    - name: Setup build environment
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          clang \
          flex \
          g++ \
          gawk \
          gcc-multilib \
          gettext \
          git \
          libncurses5-dev \
          libssl-dev \
          python3-distutils \
          rsync \
          unzip \
          zlib1g-dev \
          libdeflate-dev

    # ================== 编译检测 ==================
    - name: Build plugin
      working-directory: ./lede
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig

        mkdir -p logs
        set -o pipefail

        make package/$PLUGIN_PATH/clean || true
        if ! make package/$PLUGIN_PATH/compile V=sc -j$(nproc) 2>&1 | tee logs/build.log; then
          echo "::error::Build failed with exit code $?"
          exit 1
        fi

        if [ ! -f bin/packages/*/luci/luci-app-macfilter*.ipk ]; then
          echo "::error::No IPK package generated"
          exit 1
        fi

    # ================== 智能报告 ==================
    - name: Generate report
      if: always()
      run: |
        echo "## Compatibility Report" > report.md
        echo "### Build Status: ${{ job.status }}" >> report.md

        if grep -q "multiple definition" lede/logs/build.log; then
          echo "❌ ​**Symbol Conflicts**" >> report.md
          grep -oP 'multiple definition of \K[^ ]+' lede/logs/build.log | sort -u >> report.md
        fi

        if grep -q "No such file" lede/logs/build.log; then
          echo "❌ ​**Missing Files**" >> report.md
          grep -oP "No such file.*'\K[^']+" lede/logs/build.log | sort -u >> report.md
        fi

        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ ​**Validation Passed**" >> report.md
          echo "Generated IPK: $(ls lede/bin/packages/*/luci/luci-app-macfilter*.ipk)" >> report.md
        fi

    # ================== 结果处理 ==================
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-report
        path: |
          lede/logs/build.log
          report.md
          lede/bin/packages/*/luci/luci-app-macfilter*.ipk
